---
functional:
  - Возможность авторизации через Github
  - Возможность выбора языка программирования в терминале баттла
  - Возможность просмотра повтора баттла
  - В истории есть иконка напротив никнейма, указывающая на победителя баттла
non-functional:
  - Сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров
  - Сайт должен быть способен обрабатывать большое количество трафика
implicit:
  - Участник не может писать и изменять код соперника
  - Зрители не могут писать код и вносить изменения в код участников
  - Пользователи не могут вносить изменения в таблицу лидеров вручную
  - Участники не могут вносить изменения в предустановленную задачу баттла
